export enum ErrorCode {
  UnknownError = 1,
  BadRequest = 10000,
  NothingToModify,
  InvalidKeyFormat,
  Unauthorized,
  InvalidTokenFormat,
  InvalidSignature,
  NoTokenProvided,
  NoPermissions,
  InvalidPermissions,
  InvalidChannelType,
  LoginAlreadyTaken = 20000,
  PublicKeyAlreadyRegistered,
  UnknownLogin = 30000,
  UnknownChannel,
  UnknownRole,
  UnknownMember,
  UnknownAuthRequest,
}